// Generated by Selenium IDE

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import org.openqa.selenium.By;

public class CheckoutTest extends Hooks {
  private CheckoutPage checkoutPage;

  @Before
  public void setupPageObject() {
    checkoutPage = new CheckoutPage(driver);
    driver.manage().window().maximize();
  }
  @Test
  public void checkout() throws InterruptedException {
    checkoutPage.getFoodMenu();
    checkoutPage.getAddToCart();
    checkoutPage.completeAndSubmitCart();
    checkoutPage.assertTextWhenReady(checkoutPage.pageTitle, "CHECKOUT");
    checkoutPage.completeAllMandatoryFieldsInCheckoutPage();
    checkoutPage.clickallContinueButtonsOnCheckOutPAge();
    checkoutPage.assertTextWhenReady(checkoutPage.pageTitle, "YOUR ORDER HAS BEEN RECEIVED.");

  }

  @Test
  public void checkoutMandatoryFieldsTest() throws InterruptedException {
        checkoutPage.fillMandatoryFieldExcept(checkoutPage.firstName);
    Thread.sleep(1000);
        checkoutPage.assertTextWhenReady(checkoutPage.mandatoryFirstName, "This is a required field.");
  }

  @Test
  public void checkoutLastNameFieldTest() throws InterruptedException {
    checkoutPage.fillMandatoryFieldExcept(checkoutPage.lastName);
    Thread.sleep(1000);
    checkoutPage.assertTextWhenReady(checkoutPage.mandatoryLastName, "This is a required field.");
  }
  @Test
  public void checkoutAddressFieldTest() throws InterruptedException {
    checkoutPage.fillMandatoryFieldExcept(checkoutPage.street1);
    Thread.sleep(1000);
    checkoutPage.assertTextWhenReady(checkoutPage.mandatoryStreet1,"This is a required field.");
  }
  @Test
  public void checkoutCityFieldTest() throws InterruptedException {
    checkoutPage.fillMandatoryFieldExcept(checkoutPage.cityAdress);
    Thread.sleep(1000);
    checkoutPage.assertTextWhenReady(checkoutPage.mandatoryCity, "This is a required field.");
  }


}


